[theme]
primaryColor = "#0077B6"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F4F8"
textColor = "#264653"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
headless = true
